### ISSUE TITLE
Broken example: journal_with_data_manipulation.py

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#87]
I tested with your current abstracted_database
```
INFO:pysimplesql:Executing query: SELECT Journal.* FROM Journal  LEFT JOIN Mood ON Journal.mood_id=Mood.id  ORDER BY entry_date DESC None
Traceback (most recent call last):
  File "C:\Users\Sam\Documents\GitHub\pysimplesql\examples\journal_with_data_manipulation.py", line 74, in <module>
    frm['Journal'].requery()
  File "C:\Users\Sam\Documents\GitHub\pysimplesql\examples\pysimplesql.py", line 613, in requery
    self.transform(row, TFORM_DECODE)
  File "C:\Users\Sam\Documents\GitHub\pysimplesql\examples\journal_with_data_manipulation.py", line 62, in tform_date
    if col in row:
  File "C:\Users\Sam\Documents\GitHub\pysimplesql\examples\pysimplesql.py", line 2650, in __getitem__
    return self.row[item]
KeyError: 0
```

**Comment by ssweber** [comment]
Most recent updates fix this as well!

**Comment by ssweber** [comment]
All good. I've been trying to test all the examples before I commit, and so I bumped into those. I have a change in my pull request that also fixes a small issue with this example as well. Right now it can merge cleanly... 😄
